channels:
    mezzo:
        plugin: onlytv
        title: Mezzo Live HD
        page_url: http://only-tv.org/mezzo-live-hd.html
        logo_url: http://only-tv.org/images/mezzo-live-hd.png
    nat-geo-wild:
        plugin: onlytv
        title: Nat Geo Wild
        page_url: http://only-tv.org/nat-geo-wild.html
        logo_url: http://only-tv.org/images/natgeowild.png
    national-geographic:
        plugin: onlytv
        title: National Geographic
        page_url: http://only-tv.org/national-geographic.html
        logo_url: http://only-tv.org/images/natgeo.png
    viasat-nature:
        plugin: onlytv
        title: Viasat Nature
        page_url: http://only-tv.org/viasat-nature.html
        logo_url: http://only-tv.org/images/viasat_nat.png
    vh1:
        plugin: onlytv
        title: Vh1
        page_url: http://only-tv.org/vh1.html
        logo_url: http://only-tv.org/images/vh1.png
    evrokino:
        plugin: onlytv
        title: Evrokino
        page_url: http://only-tv.org/evrokino.html
        logo_url: http://only-tv.org/images/eukino.png
