channels:
  mezzo-hd:
    plugin: teliklive
    title: Mezzo Live HD
    page_url: https://telik.live/mezzo-live-hd.html
    logo_url: https://telik.live/images/mezzo-live-hd.png
  mezzo:
    plugin: teliklive
    title: Mezzo
    page_url: https://telik.live/mezzo.html
    logo_url: https://telik.live/images/mezzo.png
  nat-geo-wild:
    plugin: teliklive
    title: Nat Geo Wild
    page_url: https://telik.live/nat-geo-wild.html
    logo_url: https://telik.live/images/nat-geo-wild.png
  national-geographic:
    plugin: teliklive
    title: National Geographic
    page_url: https://telik.live/national-geographic.html
    logo_url: https://telik.live/images/national-geographic.png
  viasat-nature:
    plugin: teliklive
    title: Viasat Nature
    page_url: https://telik.live/viasat-nature.html
    logo_url: https://telik.live/images/viasat-nature.png
  cartoon-network:
    plugin: teliklive
    title: Cartoon Network
    page_url: https://telik.live/cartoon-network.html
    logo_url: https://telik.live/images/cartoon-network.png
